%% EXAMPLE: Mobile Base Station (BS)
%
% This example shows how to calculate the electric field generated by a
% mobile base station (antenna for mobile telephony) and determine safety distances.
%
% SCENARIO:
%   A GSM/LTE BS is installed on a building roof at 30 m height.
%   The antenna is directional (sector panel).
%   EIRP = 200 W (typical for urban coverage).
%   We want to verify that the E-field is < 6 V/m in accessible areas.
%
% Author: Federico Sabbadini
% Date: 2024

%% SETUP
close all; clc; clear;
addpath('../src/core');  % Functions path

%% PROBLEM PARAMETERS

% EIRP [W] - Equivalent Isotropically Radiated Power
EIRP = 200;

% Field constant k (far-field formula: E = sqrt(30*EIRP)/r)
k = sqrt(30 * EIRP);
fprintf('EIRP = %.0f W → k = %.2f\n', EIRP, k);

% Antenna type
%   'isotropic'  - theoretical reference
%   'dipole'     - doughnut pattern
%   'directional'- sector panel (typical BS)
%   'parabola'   - narrow beam
antenna_type = 'directional';

% Antenna position [m]
x_ant = 0;
y_ant = 0;
z_ant = 30;  % Height above ground

% Regulatory limits [V/m]
attention_limit = 6;    % Italian reference value
exposure_limit  = 20;   % Italian exposure limit

%% 3D COMPUTATION GRID

% Spatial range [m]
range = 50;
step = 1;  % Resolution (increase for faster calculation)

x = -range:step:range;
y = -range:step:range;
z = 0:step:range;  % Above ground only

[X, Y, Z] = meshgrid(x, y, z);

%% ELECTRIC FIELD CALCULATION

% Distance from the antenna
R = sqrt((X - x_ant).^2 + (Y - y_ant).^2 + (Z - z_ant).^2);
R(R < 0.1) = 0.1;  % Avoid singularity

% Spherical angles (relative to antenna)
dx = X - x_ant;
dy = Y - y_ant;
dz = Z - z_ant;

theta = acos(dz ./ R);  % Zenith angle
phi   = atan2(dy, dx);  % Azimuth angle

% Radiation pattern
switch antenna_type
    case 'isotropic'
        F = ones(size(R));
        antenna_name = 'Isotropic';
    case 'dipole'
        F = abs(sin(theta));
        antenna_name = 'Dipole';
    case 'directional'
        F = abs(sin(theta) .* cos(phi));  % Main lobe toward +x
        antenna_name = 'Directional (sector)';
    case 'parabola'
        F = cos(theta).^4;
        F(theta > pi/3) = 0;  % Narrow beam
        antenna_name = 'Parabolic';
end

% Electric field [V/m]
E = k .* F ./ R;

%% VISUALIZATION 1: 6 V/m ISOSURFACE

figure('Name', '6 V/m Isosurface', 'Position', [100, 100, 800, 700]);

% Isosurface
p = patch(isosurface(x, y, z, E, attention_limit));
set(p, 'FaceColor', [1, 0.6, 0.2], 'EdgeColor', 'none', 'FaceAlpha', 0.6);

% Lighting
camlight('headlight');
lighting gouraud;

% Antenna
hold on;
plot3(x_ant, y_ant, z_ant, 'r^', 'MarkerSize', 20, 'MarkerFaceColor', 'r', 'LineWidth', 2);
text(x_ant, y_ant, z_ant + 3, 'ANTENNA', 'FontSize', 12, 'FontWeight', 'bold', ...
     'HorizontalAlignment', 'center');

% Ground plane
[Xg, Yg] = meshgrid(x, y);
surf(Xg, Yg, zeros(size(Xg)), 'FaceColor', [0.5, 0.8, 0.5], 'FaceAlpha', 0.3, 'EdgeColor', 'none');
hold off;

xlabel('x [m]');
ylabel('y [m]');
zlabel('z [m]');
title(sprintf('E = %.0f V/m Isosurface\nAntenna %s - EIRP = %.0f W', ...
              attention_limit, antenna_name, EIRP));
axis equal;
grid on;
view(45, 25);
legend('E = 6 V/m', 'Antenna', 'Location', 'northeast');
saveas(gcf, 'MobileBS_Efield_Isosurface.png');

%% VISUALIZATION 2: CHARACTERISTIC PLANES

% XZ plane (y = 0) - side view
figure('Name', 'Vertical XZ Plane', 'Position', [150, 150, 800, 500]);

idx_y0 = find(y == 0);
E_xz = squeeze(E(:, idx_y0, :))';

contourf(x, z, E_xz, 20);
colormap('hot');
cb = colorbar;
ylabel(cb, 'E [V/m]');

hold on;
% Limit contours
[c6, ~]  = contour(x, z, E_xz, [6, 6], 'g', 'LineWidth', 2);
[c20, ~] = contour(x, z, E_xz, [20, 20], 'r', 'LineWidth', 2);

% Antenna
plot(x_ant, z_ant, 'r^', 'MarkerSize', 15, 'MarkerFaceColor', 'r');

% Ground
plot(x, zeros(size(x)), 'k-', 'LineWidth', 3);
hold off;

xlabel('x [m]');
ylabel('z [m] (height)');
title(sprintf('E Field in XZ Plane - Antenna %s', antenna_name));
legend('E Field', 'E = 6 V/m', 'E = 20 V/m', 'Antenna', 'Location', 'northeast');
axis equal;
grid on;
saveas(gcf, 'MobileBS_Efield_XZPlane.png');

% XY plane (z = 1.5 m) - human height
figure('Name', 'Horizontal Plane (z = 1.5 m)', 'Position', [200, 200, 800, 600]);

z_human = 1.5;  % Typical height
idx_z = find(z >= z_human, 1);
E_xy = squeeze(E(:, :, idx_z));

contourf(x, y, E_xy, 20);
colormap('hot');
cb = colorbar;
ylabel(cb, 'E [V/m]');

hold on;
[c6, ~] = contour(x, y, E_xy, [6, 6], 'g', 'LineWidth', 2);
plot(x_ant, y_ant, 'r^', 'MarkerSize', 15, 'MarkerFaceColor', 'r');
hold off;

xlabel('x [m]');
ylabel('y [m]');
title(sprintf('E Field at %.1f m above ground (human height)', z_human));
legend('E Field', 'E = 6 V/m', 'Antenna', 'Location', 'northeast');
axis equal;
grid on;
saveas(gcf, 'MobileBS_Efield_XYPlane_HumanHeight.png');
%% SAFETY DISTANCE ANALYSIS

fprintf('\n========================================\n');
fprintf('MOBILE BASE STATION ANALYSIS\n');
fprintf('========================================\n\n');
fprintf('Parameters:\n');
fprintf('  Antenna type: %s\n', antenna_name);
fprintf('  EIRP: %.0f W\n', EIRP);
fprintf('  Antenna height: %.0f m\n', z_ant);
fprintf('  Field constant k: %.2f\n\n', k);

% Theoretical distances for isotropic antenna
r_6V  = k / 6;
r_20V = k / 20;
fprintf('Theoretical distances (isotropic antenna):\n');
fprintf('  E = 6 V/m:  %.1f m\n', r_6V);
fprintf('  E = 20 V/m: %.1f m\n\n', r_20V);

% Field at ground below antenna
E_below = E(y==0, x==0, z==0);
fprintf('E Field at ground (under antenna): %.2f V/m\n', E_below);

% Field at 50 m horizontal distance
idx_50m = find(x >= 50, 1);
E_50m = E(y==0, idx_50m, idx_z);
fprintf('E Field at 50 m (human height): %.2f V/m\n\n', E_50m);

% Compliance check
if max(E_xy(:)) < attention_limit
    fprintf('✓ E Field < 6 V/m at human level throughout the area\n');
else
    fprintf('✗ Warning: some areas exceed 6 V/m at human level\n');
end

fprintf('\n========================================\n');
fprintf('Note: for directional antennas, the maximum field\n');
fprintf('occurs along the pointing direction.\n');
fprintf('========================================\n');