%% EXAMPLE: Three-Phase 380 kV Power Line
%
% This example shows how to calculate the magnetic field generated by a
% high-voltage power line (380 kV) with a three-phase configuration.
%
% SCENARIO:
%   A 380 kV power line passes 15 meters above the ground.
%   The three conductors are arranged horizontally with 8 meters spacing.
%   The RMS current is 1000 A.
%   We want to determine the safety clearance.
%
% Author: Federico Sabbadini
% Date: 2024

%% SETUP
close all; clc; clear;
addpath('../src/core');  % Functions path

%% PROBLEM PARAMETERS

% RMS current in the line [A]
I0 = 1000;

% Positions of the three conductors (horizontal three-phase system)
%   Phase R: x = -8 m
%   Phase S: x =  0 m (center)
%   Phase T: x = +8 m
%   All at 15 m above ground
conductor_height = 15;  % [m]
spacing = 8;            % [m]

conductors = [-spacing, conductor_height;   % Phase R
                0,       conductor_height;   % Phase S
                spacing, conductor_height];  % Phase T

% Three-phase phase shift (120° between phases)
phases = [0, 2*pi/3, 4*pi/3];  % radians

%% COMPUTATION GRID

% Area of interest: from -60 to +60 m in x, from 0 to 40 m in y (above ground)
x = -60:0.5:60;
y = 0:0.5:40;
[X, Y] = meshgrid(x, y);

%% MAGNETIC FIELD CALCULATION

% Vacuum permeability
mu0 = 4*pi*1e-7;

% Initialize field components
Bx_total = zeros(size(X));
By_total = zeros(size(Y));

% Sum contributions from the three conductors
for i = 1:3
    % Complex current (with phase shift)
    I = I0 * exp(1j * phases(i));
    
    % Conductor position
    xc = conductors(i, 1);
    yc = conductors(i, 2);
    
    % Distance to observation points
    R = sqrt((X - xc).^2 + (Y - yc).^2);
    R(R < 0.01) = 0.01;  % Avoid division by zero
    
    % Magnetic field magnitude
    B = mu0 * I ./ (2 * pi * R);
    
    % Components (tangential to circle around conductor)
    Bx = -B .* (Y - yc) ./ R;
    By =  B .* (X - xc) ./ R;
    
    % Vector sum
    Bx_total = Bx_total + Bx;
    By_total = By_total + By;
end

% Total field magnitude [T] → [μT]
B_total = sqrt(abs(Bx_total).^2 + abs(By_total).^2);
B_uT = B_total * 1e6;

%% VISUALIZATION

% --- Figure 1: 3D surface of the field ---
figure('Name', 'B Field - Three-Phase 380 kV Line', 'Position', [100, 100, 800, 600]);
surf(x, y, B_uT, 'EdgeColor', 'none');
colormap('hot');
colorbar;
xlabel('Horizontal distance [m]');
ylabel('Height above ground [m]');
zlabel('B [μT]');
title('Magnetic Field - 380 kV Three-Phase Line');
view(45, 30);
grid on;

% Mark conductors
hold on;
for i = 1:3
    plot3(conductors(i,1), conductors(i,2), max(B_uT(:))/2, 'ko', 'MarkerSize', 15, 'MarkerFaceColor', 'b');
end
hold off;
saveas(gcf, 'ThreePhase_380kV_Bfield_3D.png');

% --- Figure 2: Contour lines (regulatory limits) ---
figure('Name', 'Magnetic Field Contours - Regulatory Limits', 'Position', [150, 150, 800, 600]);

% Limits: 3 μT (quality), 10 μT (attention), 100 μT (exposure)
levels = [0.3, 1, 3, 10, 30, 100];
[c, h] = contour(x, y, B_uT, levels, 'LineWidth', 1.5);
clabel(c, h, 'FontSize', 10);
colormap('jet');
colorbar;

% Highlight regulatory limits
hold on;
[c3, ~] = contour(x, y, B_uT, [3, 3], 'g', 'LineWidth', 3);
[c10, ~] = contour(x, y, B_uT, [10, 10], 'y', 'LineWidth', 3);
[c100, ~] = contour(x, y, B_uT, [100, 100], 'r', 'LineWidth', 3);

% Mark conductors
for i = 1:3
    plot(conductors(i,1), conductors(i,2), 'ko', 'MarkerSize', 12, 'MarkerFaceColor', 'b');
end

% Ground line
plot([-60, 60], [0, 0], 'k-', 'LineWidth', 2);
text(0, -2, 'GROUND', 'HorizontalAlignment', 'center', 'FontWeight', 'bold');

hold off;

xlabel('Horizontal distance [m]');
ylabel('Height above ground [m]');
title('Magnetic Field Contours - Italian Regulatory Limits');
legend('Contours', '3 μT (Quality)', '10 μT (Attention)', '100 μT (Exposure)', ...
       'Location', 'northeast');
axis equal;
grid on;
ylim([0, 40]);
saveas(gcf, 'ThreePhase_380kV_Bfield_Contours.png');

% --- Figure 3: Field profile at ground level ---
figure('Name', 'B Field Profile at Ground', 'Position', [200, 200, 800, 400]);

% Extract field at near-ground level (y = 1 m to avoid singularity)
idx_ground = find(y >= 1, 1);
B_ground = B_uT(idx_ground, :);

plot(x, B_ground, 'b-', 'LineWidth', 2);
hold on;

% Limit lines
yline(100, 'r--', '100 μT', 'LineWidth', 1.5, 'LabelHorizontalAlignment', 'left');
yline(10, 'y--', '10 μT', 'LineWidth', 1.5, 'LabelHorizontalAlignment', 'left');
yline(3, 'g--', '3 μT', 'LineWidth', 1.5, 'LabelHorizontalAlignment', 'left');

hold off;

xlabel('Distance from line [m]');
ylabel('B Field [μT]');
title(sprintf('B Field Profile at %.0f m Above Ground', y(idx_ground)));
grid on;
xlim([-60, 60]);
ylim([0, max(B_ground)*1.1]);
saveas(gcf, 'ThreePhase_380kV_Bfield_GroundProfile.png');

%% SAFETY DISTANCE ANALYSIS

fprintf('\n========================================\n');
fprintf('THREE-PHASE 380 kV LINE ANALYSIS\n');
fprintf('========================================\n\n');
fprintf('Parameters:\n');
fprintf('  Current: %d A (RMS)\n', I0);
fprintf('  Conductor height: %.0f m\n', conductor_height);
fprintf('  Conductor spacing: %.0f m\n\n', spacing);

fprintf('B Field at near-ground level (under the line): %.2f μT\n\n', B_uT(idx_ground, x==0));

% Find distances for different limits
analysis_limits = [100, 10, 3];
names = {'Exposure limit', 'Attention level', 'Quality target'};

fprintf('Safety distances (from line center):\n');
for i = 1:length(analysis_limits)
    lvl = analysis_limits(i);
    
    % Find where field drops below limit
    idx_ok = find(B_ground < lvl);
    if ~isempty(idx_ok)
        % Take minimum distance (closest to center)
        dist = min(abs(x(idx_ok)));
        fprintf('  %s (%d μT): %.1f m\n', names{i}, lvl, dist);
    else
        fprintf('  %s (%d μT): always below limit\n', names{i}, lvl);
    end
end

fprintf('\n========================================\n');
fprintf('Note: the safety clearance for new constructions\n');
fprintf('should be calculated based on the 3 μT value.\n');
fprintf('========================================\n');